cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_node"

authors = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib"]
name = "modelfox_node"
path = "lib.rs"

[build-dependencies]
reqwest = { workspace = true }

[dependencies]
anyhow = { workspace = true }
memmap = { workspace = true }
node_api = { workspace = true }
serde = { workspace = true }

modelfox_core = { workspace = true }
modelfox_model = { workspace = true }
