[toolchain]
channel = "nightly-2022-07-03"
components = [ "clippy", "rustfmt" ]
targets = [ 
	"aarch64-unknown-linux-gnu",
	"aarch64-unknown-linux-musl",
	"aarch64-apple-darwin",
	"wasm32-unknown-unknown",
	"x86_64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
	"x86_64-apple-darwin",
	"x86_64-pc-windows-gnu",
	"x86_64-pc-windows-msvc",
]
