cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_www_content"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"
doctest = false

[dependencies]
anyhow = { workspace = true }
pinwheel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sunfish = { workspace = true }

modelfox_ui = { workspace = true }
