cargo-features = ["workspace-inheritance"]

[package]
name = "wheel_writer"

authors = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
name = "wheel_writer"
path = "lib.rs"

[[bin]]
name = "wheel_writer"
path = "main.rs"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
digest = { workspace = true }
indoc = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
textwrap = { workspace = true }
time = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true }
