cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_www_index_common"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
num = { workspace = true }
pinwheel = { workspace = true }
serde = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }

modelfox_ui = { workspace = true }