cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_tree"

description = { workspace = true }
publish = true
authors = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }


[lib]
path = "lib.rs"

[features]
default = []
timing = []

[[bin]]
name = "modelfox_tree_benchmarks"
path = "benchmarks/main.rs"

[[bin]]
name = "modelfox_tree_benchmark_allstate"
path = "benchmarks/allstate.rs"

[[bin]]
name = "modelfox_tree_benchmark_boston"
path = "benchmarks/boston.rs"

[[bin]]
name = "modelfox_tree_benchmark_census"
path = "benchmarks/census.rs"

[[bin]]
name = "modelfox_tree_benchmark_flights"
path = "benchmarks/flights.rs"

[[bin]]
name = "modelfox_tree_benchmark_heart_disease"
path = "benchmarks/heart_disease.rs"

[[bin]]
name = "modelfox_tree_benchmark_higgs"
path = "benchmarks/higgs.rs"

[[bin]]
name = "modelfox_tree_benchmark_iris"
path = "benchmarks/iris.rs"

[dependencies]
bitvec = { workspace = true }
buffalo = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
num = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

modelfox_finite = { workspace = true }
modelfox_kill_chip = { workspace = true }
modelfox_metrics = { workspace = true }
modelfox_progress_counter = { workspace = true }
modelfox_table = { workspace = true }
modelfox_zip = { workspace = true }
