cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_production_metrics"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
ndarray = { workspace = true }
num = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }

modelfox_model = { workspace = true }
modelfox_zip = { workspace = true }

modelfox_app_date_window = { path = "../date_window" }
modelfox_app_monitor_event = { path = "../monitor_event" }
modelfox_app_production_stats = { path = "../production_stats" }

[dev-dependencies]
insta = { workspace = true }
