cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_www_docs_getting_started_monitor_server"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
pinwheel = { workspace = true }
modelfox_charts = { workspace = true }
sunfish = { workspace = true }

modelfox_ui = { workspace = true }

modelfox_app_core = { workspace = true }
modelfox_app_date_window = { path = "../../../../../../app/date_window" }
modelfox_app_production_stats_column_server = { path = "../../../../../../app/routes/repos/_/models/_/production_stats/columns/_/server"}
modelfox_app_production_stats_index_server = { path = "../../../../../../app/routes/repos/_/models/_/production_stats/index/server"}
modelfox_app_ui = { path = "../../../../../../app/ui" }
modelfox_www_layouts = { path = "../../../../../layouts" }
modelfox_www_ui = { path = "../../../../../ui" }