cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_production_stats_index_client"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "modelfox_app_production_stats_index_client"
path = "main.rs"

[dependencies]
pinwheel = { workspace = true }
web-sys = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_ui = { workspace = true }