cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_track_server"

license = "UNLICENSED"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
memmap = { workspace = true }
num = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
sunfish = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

modelfox_core = { workspace = true }
modelfox_id = { workspace = true }
modelfox_model = { workspace = true }

modelfox_app_context = { path = "../../../context" }
modelfox_app_core = { path = "../../../core" }
modelfox_app_monitor_event = { path = "../../../monitor_event" }