cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_date_window"

license = "UNLICENSED"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
serde = { workspace = true }
