cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_www_benchmarks_client"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "modelfox_www_benchmarks_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = { workspace = true }
pinwheel = { workspace = true }
web-sys = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_ui = { workspace = true }

modelfox_www_benchmarks_common = { path = "../common" }