cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_training_stats_column_client"

license = "UNLICENSED"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "modelfox_app_training_stats_column_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = { workspace = true }
pinwheel = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_ui = { workspace = true }