cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_context"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
sunfish = { workspace = true }

modelfox_app_core = { path = "../core" }