cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_training_grid_common"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
num = { workspace = true }
pinwheel = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_core = { workspace = true }
modelfox_id = { workspace = true }
modelfox_model = { workspace = true }
modelfox_ui = { workspace = true }

modelfox_app_core = { path = "../../../../../../../core" }