cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_playground_common"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
pinwheel = { workspace = true }
serde = { workspace = true }

modelfox_charts = { workspace = true }
