cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_text"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = true
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
fnv = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
