cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_new_model_client"

license = "UNLICENSED"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "modelfox_app_new_model_client"
path = "main.rs"

[dependencies]
modelfox_ui = { workspace = true }
web-sys = { workspace = true }
