cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_elixir"

authors = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib"]
name = "modelfox_elixir"
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
erl_nif = { workspace = true }
memmap = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }

modelfox_core = { workspace = true }
modelfox_model = { workspace = true }