cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_www_blog_index_server"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
pinwheel = { workspace = true }
sunfish = { workspace = true }

modelfox_ui = { workspace = true }

modelfox_www_content = { path = "../../../../content" }
modelfox_www_layouts = { path = "../../../../layouts" }
