cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_login_server"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
lettre = { workspace = true }
pinwheel = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
sqlx = { workspace = true }
sunfish = { workspace = true }
url = { workspace = true }

modelfox_id = { workspace = true }
modelfox_ui = { workspace = true }

modelfox_app_context = { path = "../../../context" }
modelfox_app_core = { path = "../../../core" }
modelfox_app_layouts = { path = "../../../layouts" }