cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_core"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dev-dependencies]
insta = { workspace = true }
modelfox_serve = { workspace = true }
tracing-test = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
fnv = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
lettre = { workspace = true }
memmap = { workspace = true }
ndarray = { workspace = true }
num = { workspace = true }
rand = { workspace = true }
rust-s3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
sunfish = { workspace = true }
time = { workspace = true, features = ["formatting", "macros"] }
tokio = { workspace = true, features = ["full", "time", "test-util"] }
tracing = { workspace = true }
url = { workspace = true }

modelfox_core = { workspace = true }
modelfox_finite = { workspace = true }
modelfox_id = { workspace = true }
modelfox_metrics = { workspace = true }
modelfox_model = { workspace = true }
modelfox_table = { workspace = true }
modelfox_text = { workspace = true }
modelfox_zip = { workspace = true }

modelfox_app_migrations = { path = "../migrations" }
modelfox_app_monitor_event = { path = "../monitor_event" }
modelfox_app_production_metrics = { path = "../production_metrics" }
modelfox_app_production_stats = { path = "../production_stats" }