cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_model"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = true
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
buffalo = { workspace = true }
fnv = { workspace = true }
num = { workspace = true }

modelfox_linear = { workspace = true }
modelfox_text = { workspace = true }
modelfox_tree = { workspace = true }
