cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_www_index_server"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
futures = { workspace = true }
pinwheel = { workspace = true }
sunfish = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_finite = { workspace = true }
modelfox_ui = { workspace = true }

modelfox_www_index_common = { path = "../common" }
modelfox_www_layouts = { path = "../../../layouts" }
modelfox_www_ui = { path = "../../../ui" }
