cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_production_class_metrics_server"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
num = { workspace = true }
pinwheel = { workspace = true }
serde = { workspace = true }
serde_urlencoded = { workspace = true }
sunfish = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_core = { workspace = true }
modelfox_finite = { workspace = true }
modelfox_id = { workspace = true }
modelfox_model = { workspace = true }
modelfox_ui = { workspace = true }
modelfox_zip = { workspace = true }

modelfox_app_context = { path = "../../../../../../../../context" }
modelfox_app_core = { path = "../../../../../../../../core" }
modelfox_app_date_window = { path = "../../../../../../../../date_window" }
modelfox_app_layouts = { path = "../../../../../../../../layouts" }
modelfox_app_production_metrics = { path = "../../../../../../../../production_metrics" }
modelfox_app_ui = { path = "../../../../../../../../ui" }