#!/bin/sh
for arg do
  shift
  [ "$arg" = "-lwinapi_advapi32" ] && continue
  [ "$arg" = "-lwinapi_cfgmgr32" ] && continue
  [ "$arg" = "-lwinapi_credui" ] && continue
  [ "$arg" = "-lwinapi_fwpuclnt" ] && continue
  [ "$arg" = "-lwinapi_gdi32" ] && continue
  [ "$arg" = "-lwinapi_kernel32" ] && continue
  [ "$arg" = "-lwinapi_msimg32" ] && continue
  [ "$arg" = "-lwinapi_mswsock" ] && continue
  [ "$arg" = "-lwinapi_ntdll" ] && continue
  [ "$arg" = "-lwinapi_ole32" ] && continue
  [ "$arg" = "-lwinapi_opengl32" ] && continue
  [ "$arg" = "-lwinapi_secur32" ] && continue
  [ "$arg" = "-lwinapi_shell32" ] && continue
  [ "$arg" = "-lwinapi_synchronization" ] && continue
  [ "$arg" = "-lwinapi_user32" ] && continue
  [ "$arg" = "-lwinapi_winspool" ] && continue
  [ "$arg" = "-lwinapi_ws2_32" ] && continue
  set -- "$@" "$arg"
done
zig cc -target x86_64-windows-gnu -lstdc++ $@
