cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_training_class_metrics_client"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = "UNLICENSED"
publish = false
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "modelfox_app_training_class_metrics_client"
path = "main.rs"

[dependencies]
modelfox_ui = { workspace = true }
