cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_app_training_metrics_precision_recall_client"

license = "UNLICENSED"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[[bin]]
name = "modelfox_app_training_metrics_precision_recall_client"
path = "main.rs"

[dependencies]
pinwheel = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_ui = { workspace = true }
