cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_www_benchmarks_common"

authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
version = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
futures-signals = { workspace = true }
num = { workspace = true }
pinwheel = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

modelfox_charts = { workspace = true }
modelfox_ui = { workspace = true }