//! https://developer.mozilla.org/en-US/docs/Web/SVG/Element

use pinwheel_elements_macro::element;

element!(namespace = "svg", tag = "a");
element!(namespace = "svg", tag = "altGlyph");
element!(namespace = "svg", tag = "altGlyphDef");
element!(namespace = "svg", tag = "altGlyphItem");
element!(namespace = "svg", tag = "animate");
element!(namespace = "svg", tag = "animateColor");
element!(namespace = "svg", tag = "animateMotion");
element!(namespace = "svg", tag = "animateTransform");
element!(namespace = "svg", tag = "circle");
element!(namespace = "svg", tag = "clipPath");
// element!(namespace = "svg", tag = "color-profile");
element!(namespace = "svg", tag = "cursor");
element!(namespace = "svg", tag = "defs");
element!(namespace = "svg", tag = "desc");
element!(namespace = "svg", tag = "discard");
element!(namespace = "svg", tag = "ellipse");
element!(namespace = "svg", tag = "feBlend");
element!(namespace = "svg", tag = "feColorMatrix");
element!(namespace = "svg", tag = "feComponentTransfer");
element!(namespace = "svg", tag = "feComposite");
element!(namespace = "svg", tag = "feConvolveMatrix");
element!(namespace = "svg", tag = "feDiffuseLighting");
element!(namespace = "svg", tag = "feDisplacementMap");
element!(namespace = "svg", tag = "feDistantLight");
element!(namespace = "svg", tag = "feDropShadow");
element!(namespace = "svg", tag = "feFloodfeFuncA");
element!(namespace = "svg", tag = "feFuncB");
element!(namespace = "svg", tag = "feFuncG");
element!(namespace = "svg", tag = "feFuncRfeGaussianBlur");
element!(namespace = "svg", tag = "feImage");
element!(namespace = "svg", tag = "feMerge");
element!(namespace = "svg", tag = "feMergeNode");
element!(namespace = "svg", tag = "feMorphology");
element!(namespace = "svg", tag = "feOffset");
element!(namespace = "svg", tag = "fePointLight");
element!(namespace = "svg", tag = "feSpecularLighting");
element!(namespace = "svg", tag = "feSpotLight");
element!(namespace = "svg", tag = "feTile");
element!(namespace = "svg", tag = "feTurbulence");
element!(namespace = "svg", tag = "filter");
// element!(namespace = "svg", tag = "font-face-format");
// element!(namespace = "svg", tag = "font-face-name");
// element!(namespace = "svg", tag = "font-face-src");
// element!(namespace = "svg", tag = "font-face-uri");
// element!(namespace = "svg", tag = "font-face");
element!(namespace = "svg", tag = "font");
element!(namespace = "svg", tag = "foreignObject");
element!(namespace = "svg", tag = "g");
element!(namespace = "svg", tag = "glyph");
element!(namespace = "svg", tag = "glyphRef");
element!(namespace = "svg", tag = "hatch");
element!(namespace = "svg", tag = "hatchpath");
element!(namespace = "svg", tag = "hkern");
element!(namespace = "svg", tag = "image");
element!(namespace = "svg", tag = "line");
element!(namespace = "svg", tag = "linearGradient");
element!(namespace = "svg", tag = "marker");
element!(namespace = "svg", tag = "mask");
element!(namespace = "svg", tag = "mesh");
element!(namespace = "svg", tag = "meshgradient");
element!(namespace = "svg", tag = "meshpatch");
element!(namespace = "svg", tag = "meshrow");
element!(namespace = "svg", tag = "metadata");
// element!(namespace = "svg", tag = "missing-glyph");
element!(namespace = "svg", tag = "mpath");
element!(namespace = "svg", tag = "path");
element!(namespace = "svg", tag = "pattern");
element!(namespace = "svg", tag = "polygon");
element!(namespace = "svg", tag = "polyline");
element!(namespace = "svg", tag = "radialGradient");
element!(namespace = "svg", tag = "rect");
element!(namespace = "svg", tag = "script");
element!(namespace = "svg", tag = "set");
element!(namespace = "svg", tag = "solidcolor");
element!(namespace = "svg", tag = "stop");
element!(namespace = "svg", tag = "style");
element!(namespace = "svg", tag = "svg");
element!(namespace = "svg", tag = "switch");
element!(namespace = "svg", tag = "symbol");
element!(namespace = "svg", tag = "textPath");
element!(namespace = "svg", tag = "title");
element!(namespace = "svg", tag = "tref");
element!(namespace = "svg", tag = "tspan");
element!(namespace = "svg", tag = "unknown");
// element!(namespace = "svg", tag = "use");
element!(namespace = "svg", tag = "view");
element!(namespace = "svg", tag = "vkern");
